name: PEX Builder

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: make install

    - name: Create PEX File
      run: make pex

    - name: Run aptstract help command to test file
      run: ./aptstract.pex --help

    - name: Upload PEX File to Release
      if: github.event_name == 'release'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        gh release upload ${{ github.event.release.tag_name }} aptstract.pex
